server:
  port: 8087
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false #是否注册到注册中心，本身无需注册
    fetch-registry: false #是否从Eureka中获取注册信息
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka